### ISSUE TITLE
Grammar in endless loop errors

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-textmate#40]
_From @jrieken on April 3, 2017 9:55_

* have the below cpp-file
* :bug: an error about the grammar being in an endless loop appears

```cpp


#include <windows.h>

#ifdef


```

_Copied from original issue: Microsoft/vscode#23850_

**Comment by aeschli** [comment]
The problem is https://github.com/Microsoft/vscode/blob/master/extensions/cpp/syntaxes/c.json#L775
```
{
					"begin": "\\G",
					"end": "(?=//)|(?=/\\*(?!.*\\\\\\s*\\n))|(?<!\\\\)(?=\\n)",
					"name": "meta.preprocessor.c",
					"patterns": [
						{
							"include": "#preprocessor-rule-conditional-line"
						}
					]
				}
```
Because of the fix for https://github.com/Microsoft/vscode-textmate/issues/12
we recover by entering the rule and go to the next line.

Moving to vscode-textmate

**Comment by aeschli** [comment]
C-Grammar issue discussing this: https://github.com/atom/language-c/issues/218#issuecomment-291886023

**Comment by sean-mcmanus** [comment]
Can you give an update on what the plan is to fix this? Is someone on the VS Code team going to fix it or did you want someone on the C++ extension team to do it?

**Comment by aeschli** [comment]
I have it on my to-do list. But if you have resources to do it, I wouldn't resist. :-)

**Comment by aeschli** [comment]
I pushed a change to the C grammar (see https://github.com/Microsoft/vscode/issues/23850) to avoid the endless loop case. Also proposed to the atom grammar: https://github.com/atom/language-c/pull/237

**Comment by sean-mcmanus** [comment]
Thanks a lot for the fix.

**Comment by sean-mcmanus** [comment]
@aeschli Was this fixed? I'm still seeing the bug in Insiders.

**Comment by aeschli** [comment]
@sean-mcmanus The fix got lost as my pull request didn't get accepted yet. I improved it and reapplied it: https://github.com/Microsoft/vscode/commit/e671ee9722f1a2da17157c3f6021225d208ac363

**Comment by alexandrudima** [comment]
I have removed the console.error since this is not really an error.
